package com.jolaar.personalwebsite.common.enums;

public enum SkillCategory {
    PROGRAMMING_LANGUAGES,
    WEB_TECHNOLOGIES,
    BACKEND_TECHNOLOGIES,
    CONTAINERIZATION,
    DATABASES,
    CLOUD,
    DEVOPS,
    IDE,
    TOOLS, // eg.Postman
    VERSION_CONTROL,
    TESTING,
    ALGORITHMS_AND_DATA_STRUCTURES,
    SOFTWARE_DESIGN_AND_ARCHITECTURE,
    SOFT_SKILLS
}
